/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlockItem: typeof import('./components/BlockItem.vue')['default']
    BlockItems: typeof import('./components/BlockItems.vue')['default']
    ItemCard: typeof import('./components/ItemCard.vue')['default']
    ItemsPage: typeof import('./pages/ItemsPage.vue')['default']
    VSelect: typeof import('./components/VSelect.vue')['default']
  }
}
